project:
  type: website
  output-dir: docs

website:
  title: "Media Server Guide"
  sidebar:
    style: "floating"
    search: true
    contents:
       - index.qmd
       - demo.qmd
       - section: "Basics"
         contents:
           - hardwareos.qmd
           - setup.qmd
           - access.qmd
       - section: "Advanced"
         contents:
           - domains.qmd
           - configuration.qmd
           - accounts.qmd
           - iptv.qmd
       - about.qmd
  page-footer:
    left: 
      - "Â© 2026 Michael Leiby"
      - icon: github
        href: https://github.com/BandguyMichael
      - "Created with Quarto"

format:
  html:
    theme: architect  
    fontsize: 1.1em
    css: styles.css
    toc: true