project:
  type: website
  output-dir: docs

website:
  title: "Quarto"
  sidebar:
    style: "floating"
    search: true
    contents:
       - index.qmd
       - section: "Basics"
         contents:
           - hardwareos.qmd
           - setup.qmd
           - access.qmd
       - section: "Advanced"
         contents:
           - domains.qmd
           - configuration.qmd
           - accounts.qmd
           - iptv.qmd
       - about.qmd

format:
  html:
    theme: architect  
    fontsize: 1.1em
    css: styles.css
    toc: true